<?php
$ship_code_array = array();
$ship_code_array[0]["code"] = 'TPIB_G2';  $ship_code_array[0]['name'] = '3PD Logistics Solutions - Basic Service';
$ship_code_array[1]["code"] = 'TPIB_09';  $ship_code_array[1]['name'] = '3PD Logistics Solutions - Delivery and Install';		
$ship_code_array[2]["code"] = 'TPIB_DS';  $ship_code_array[2]['name'] = '3PD Logistics Solutions - Threshold Service';		
$ship_code_array[3]["code"] = 'ANBS_G2';  $ship_code_array[3]['name'] = 'A&B Courier - Basic Service';		
$ship_code_array[4]["code"] = 'ANBS_CG';  $ship_code_array[4]['name'] = 'A&B Courier - Ground';		
$ship_code_array[5]["code"] = 'ANBS_DS';  $ship_code_array[5]['name'] = 'A&B Courier - Threshold Service';		
$ship_code_array[6]["code"] = 'PYLR';  $ship_code_array[6]['name'] = 'A. Duie Pyle Inc.';		
$ship_code_array[7]["code"] = 'PYLR_SE';  $ship_code_array[7]['name'] = 'A. Duie Pyle Inc. - 2nd Day';		
$ship_code_array[8]["code"] = 'PYLR_ND';  $ship_code_array[8]['name'] = 'A. Duie Pyle Inc. - Next Day';		
$ship_code_array[9]["code"] = 'PYLR_DS';  $ship_code_array[9]['name'] = 'A. Duie Pyle Inc. - Threshold Service';		
$ship_code_array[10]["code"] = 'ABFS';  $ship_code_array[10]['name'] = 'ABF';		
$ship_code_array[11]["code"] = 'ABFS_SE';  $ship_code_array[11]['name'] = 'ABF - 2nd Day';		
$ship_code_array[12]["code"] = 'ABFS_G2';  $ship_code_array[12]['name'] = 'ABF - Basic Service';		
$ship_code_array[13]["code"] = 'ABFS_09';  $ship_code_array[13]['name'] = 'ABF - Delivery and Install';		
$ship_code_array[14]["code"] = 'ACOC_G2';  $ship_code_array[14]['name'] = 'ACS Inc. - Basic Service';		
$ship_code_array[15]["code"] = 'ACOC_09';  $ship_code_array[15]['name'] = 'ACS Inc. - Delivery and Install';		
$ship_code_array[16]["code"] = 'ACOC_DS';  $ship_code_array[16]['name'] = 'ACS Inc. - Threshold Service';	
$ship_code_array[17]["code"] = 'AIRB_ND';  $ship_code_array[17]['name'] = 'Airborne Freight Corp - Overnight Express';		
$ship_code_array[18]["code"] = 'AGRP_G2';  $ship_code_array[18]['name'] = 'Airgroup Express - Basic Service';		
$ship_code_array[19]["code"] = 'AGRP_09';  $ship_code_array[19]['name'] = 'Airgroup Express - Delivery and Install';		
$ship_code_array[20]["code"] = 'AGRP_DS';  $ship_code_array[20]['name'] = 'Airgroup Express - Threshold Service';		
$ship_code_array[21]["code"] = 'AITW_G2';  $ship_code_array[21]['name'] = 'AIT Worldwide Logistics - Basic Service';		
$ship_code_array[22]["code"] = 'AITW_09';  $ship_code_array[22]['name'] = 'AIT Worldwide Logistics - Delivery and Install';		
$ship_code_array[23]["code"] = 'AITW_DS';  $ship_code_array[23]['name'] = 'AIT Worldwide Logistics - Threshold Service';
$ship_code_array[24]["code"] = 'TWMC_G2';  $ship_code_array[24]['name'] = 'Alero Wordwide - Basic Service';		
$ship_code_array[25]["code"] = 'TWMC_09';  $ship_code_array[25]['name'] = 'Alero Wordwide - Delivery and Install';		
$ship_code_array[26]["code"] = 'TWMC_DS';  $ship_code_array[26]['name'] = 'Alero Wordwide - Threshold Service';
$ship_code_array[27]["code"] = 'AAIE_G2';  $ship_code_array[27]['name'] = 'ALG Worldwide Logistics - Basic Service';		
$ship_code_array[28]["code"] = 'AAIE_09';  $ship_code_array[28]['name'] = 'ALG Worldwide Logistics - Delivery and Install';		
$ship_code_array[29]["code"] = 'AAIE_DS';  $ship_code_array[29]['name'] = 'ALG Worldwide Logistics - Threshold Service';
$ship_code_array[30]["code"] = 'ASAQ_G2';  $ship_code_array[30]['name'] = 'Allstates Worldcargo - Basic Service';		
$ship_code_array[31]["code"] = 'ASAQ_09';  $ship_code_array[31]['name'] = 'Allstates Worldcargo - Delivery and Install';		
$ship_code_array[32]["code"] = 'ASAQ_DS';  $ship_code_array[32]['name'] = 'Allstates Worldcargo - Threshold Service';
$ship_code_array[33]["code"] = 'AFMI';  $ship_code_array[33]['name'] = 'Alto Freight';		
$ship_code_array[34]["code"] = 'AEWS_CG';  $ship_code_array[34]['name'] = 'American West - Ground';		
$ship_code_array[35]["code"] = 'AAUE';  $ship_code_array[35]['name'] = 'Andlauer Transportation Services';		
$ship_code_array[36]["code"] = 'AMEX';  $ship_code_array[36]['name'] = 'Apex Motor Express Ltd.';		
$ship_code_array[37]["code"] = 'AVRT';  $ship_code_array[37]['name'] = 'Averitt Express';		
$ship_code_array[38]["code"] = 'AVRT_G2';  $ship_code_array[38]['name'] = 'Averitt Express - Basic Service';		
$ship_code_array[39]["code"] = 'BMGI_G2';  $ship_code_array[39]['name'] = 'Beltmann Logistics - Basic Service';		
$ship_code_array[40]["code"] = 'BMGI_09';  $ship_code_array[40]['name'] = 'Beltmann Logistics - Delivery and Install';		
$ship_code_array[41]["code"] = 'BTVP';  $ship_code_array[41]['name'] = 'Best Overnite';		
$ship_code_array[42]["code"] = 'BTVP_G2';  $ship_code_array[42]['name'] = 'Best Overnite - Basic Service';		
$ship_code_array[43]["code"] = 'BEST';  $ship_code_array[43]['name'] = 'Bestar';		
$ship_code_array[44]["code"] = 'BVLL_09';  $ship_code_array[44]['name'] = 'Brewer VanLine Logistics - Deliver and Install';		
$ship_code_array[45]["code"] = 'BVLL_DS';  $ship_code_array[45]['name'] = 'Brewer VanLine Logistics - Threshold Service';		
$ship_code_array[46]["code"] = 'BVLL_G2';  $ship_code_array[46]['name'] = 'Brewer VanLine Logistics Inc.';		
$ship_code_array[47]["code"] = 'BTGD';  $ship_code_array[47]['name'] = 'Bullet Trucking Inc.';	 	
$ship_code_array[48]["code"] = 'RBTW';  $ship_code_array[48]['name'] = 'C.H. Robinson Worldwide Inc.';		
$ship_code_array[49]["code"] = 'RBTW_SE';  $ship_code_array[49]['name'] = 'C.H. Robinson Worldwide Inc. - 2nd Day';		
$ship_code_array[50]["code"] = 'CAOE';  $ship_code_array[50]['name'] = 'California Overnight';		
$ship_code_array[51]["code"] = 'CAOE_SE';  $ship_code_array[51]['name'] = 'California Overnight - 2nd Day';		
$ship_code_array[52]["code"] = 'CAOE_ND';  $ship_code_array[52]['name'] = 'California Overnight - Next Day';		
$ship_code_array[53]["code"] = 'CG';  $ship_code_array[53]['name'] = 'Canada Post - Expedited Parcel';		
$ship_code_array[54]["code"] = 'CG_SE';  $ship_code_array[54]['name'] = 'Canada Post - Xpresspost';		
$ship_code_array[55]["code"] = 'CFWL_G2';  $ship_code_array[55]['name'] = 'Canadian Freightways - Basic Service';		
$ship_code_array[56]["code"] = 'CNPL';  $ship_code_array[56]['name'] = 'Canpar';		
$ship_code_array[57]["code"] = 'CNPL_SE';  $ship_code_array[57]['name'] = 'Canpar - 2nd Day';		
$ship_code_array[58]["code"] = 'CXNM_G2';  $ship_code_array[58]['name'] = 'Carter Transporation - Basic Service';		
$ship_code_array[59]["code"] = 'CENF';  $ship_code_array[59]['name'] = 'Central Freight Lines';		
$ship_code_array[60]["code"] = 'CETR';  $ship_code_array[60]['name'] = 'Central Transport Inc.';		
$ship_code_array[61]["code"] = 'CEVA_G2';  $ship_code_array[61]['name'] = 'CEVA Logistics - Basic Service';		
$ship_code_array[62]["code"] = 'CEVA_09';  $ship_code_array[62]['name'] = 'CEVA Logistics - Delivery and Install';		
$ship_code_array[63]["code"] = 'CEVA_DS';  $ship_code_array[63]['name'] = 'CEVA Logistics - Threshold Service';		
$ship_code_array[64]["code"] = 'CTQH_G2';  $ship_code_array[64]['name'] = 'Champion Logistics - Basic Service ';		
$ship_code_array[65]["code"] = 'CTQH_09';  $ship_code_array[65]['name'] = 'Champion Logistics - Delivery and Install';		
$ship_code_array[66]["code"] = 'CTQH_DS';  $ship_code_array[66]['name'] = 'Champion Logistics - Threshold Service';		
$ship_code_array[67]["code"] = 'CLKE';  $ship_code_array[67]['name'] = 'Clarke Transport';		
$ship_code_array[68]["code"] = 'CEGW_SE';  $ship_code_array[68]['name'] = 'Continental Freightways - 2nd Day';		
$ship_code_array[69]["code"] = 'CWCE';  $ship_code_array[69]['name'] = 'Conway';		
$ship_code_array[70]["code"] = 'CWCE_SE';  $ship_code_array[70]['name'] = 'Conway - 2nd Day';		
$ship_code_array[71]["code"] = 'MLCT_G2';  $ship_code_array[71]['name'] = 'Crane Worldwide - Basic Service';		
$ship_code_array[72]["code"] = 'MLCT_09';  $ship_code_array[72]['name'] = 'Crane Worldwide - Delivery and Install';		
$ship_code_array[73]["code"] = 'MLCT_DS';  $ship_code_array[73]['name'] = 'Crane Worldwide - Threshold Service';		
$ship_code_array[74]["code"] = 'CFNS';  $ship_code_array[74]['name'] = 'Custom Freight Systems Inc.';	 	
$ship_code_array[75]["code"] = 'CGLY_DS';  $ship_code_array[75]['name'] = 'Custom Global Logistics - Threshold Service';		
$ship_code_array[76]["code"] = 'DTST';  $ship_code_array[76]['name'] = 'DATS Trucking Inc.';		
$ship_code_array[77]["code"] = 'DAYR';  $ship_code_array[77]['name'] = 'Day & Ross';		
$ship_code_array[78]["code"] = 'DYLT';  $ship_code_array[78]['name'] = 'Daylight Transport';		
$ship_code_array[79]["code"] = 'DAFG';  $ship_code_array[79]['name'] = 'Dayton Freight';		
$ship_code_array[80]["code"] = 'SIFF_G2';  $ship_code_array[80]['name'] = 'DB Schenker - Basic Service';		
$ship_code_array[81]["code"] = 'SIFF_09';  $ship_code_array[81]['name'] = 'DB Schenker - Delivery and Install';		
$ship_code_array[82]["code"] = 'SIFF_DS';  $ship_code_array[82]['name'] = 'DB Schenker - Threshold Service';		
$ship_code_array[83]["code"] = 'DPHE';  $ship_code_array[83]['name'] = 'Dependable Highway Express';		
$ship_code_array[84]["code"] = 'DPHE_G2';  $ship_code_array[84]['name'] = 'Dependable Highway Express - Basic Service';		
$ship_code_array[85]["code"] = 'DHL_SE';  $ship_code_array[85]['name'] = 'DHL Shipping - 2nd Day Air';		
$ship_code_array[86]["code"] = 'DHL_CG';  $ship_code_array[86]['name'] = 'DHL Shipping - Ground';		
$ship_code_array[87]["code"] = 'DHL_ND';  $ship_code_array[87]['name'] = 'DHL Shipping - Next Day Air';		
$ship_code_array[88]["code"] = 'RDMD';  $ship_code_array[88]['name'] = 'Diamond Delivery';		
$ship_code_array[89]["code"] = 'SETP_G2';  $ship_code_array[89]['name'] = 'Direct Shippers - Basic Service';		
$ship_code_array[90]["code"] = 'DHRN';  $ship_code_array[90]['name'] = 'Dohrn Transfer Co.';		
$ship_code_array[91]["code"] = 'EGLE_G2';  $ship_code_array[91]['name'] = 'Eagle Freight - Basic Service';		
$ship_code_array[92]["code"] = 'EGLE_09';  $ship_code_array[92]['name'] = 'Eagle Freight - Delivery and Install';		
$ship_code_array[93]["code"] = 'EAGL_DS';  $ship_code_array[93]['name'] = 'Eagle Freight - Threshold Service';		
$ship_code_array[94]["code"] = 'ECHS_G2';  $ship_code_array[94]['name'] = 'Echo Global Logistics - Basic Service';		
$ship_code_array[95]["code"] = 'ECHS_09';  $ship_code_array[95]['name'] = 'Echo Global Logistics - Delivery and Install';		
$ship_code_array[96]["code"] = 'ECHS_DS';  $ship_code_array[96]['name'] = 'Echo Global Logistics - Threshold Service';		
$ship_code_array[97]["code"] = 'EPCE';  $ship_code_array[97]['name'] = 'Epic Express';		
$ship_code_array[98]["code"] = 'EXLA';  $ship_code_array[98]['name'] = 'Estes Express Lines';		
$ship_code_array[99]["code"] = 'EXLA_SE';  $ship_code_array[99]['name'] = 'Estes Express Lines - 2nd Day';		
$ship_code_array[100]["code"] = 'EXLA_G2';  $ship_code_array[100]['name'] = 'Estes Express Lines - Basic Service';		
$ship_code_array[101]["code"] = 'EXLA_09';  $ship_code_array[101]['name'] = 'Estes Express Lines - Delivery and Install';		
$ship_code_array[102]["code"] = 'EXLA_DS';  $ship_code_array[102]['name'] = 'Estes Express Lines - Threshold Service';		
$ship_code_array[103]["code"] = 'EFWW_G2';  $ship_code_array[103]['name'] = 'Estes Forwarding Worldwide - Basic Service';		
$ship_code_array[104]["code"] = 'EFWW_09';  $ship_code_array[104]['name'] = 'Estes Forwarding Worldwide - Delivery and Install';		
$ship_code_array[105]["code"] = 'EFWW_DS';  $ship_code_array[105]['name'] = 'Estes Forwarding Worldwide - Threshold Service';		
$ship_code_array[106]["code"] = 'ELGS_G2';  $ship_code_array[106]['name'] = 'Exel Logistics - Basic Service';		
$ship_code_array[107]["code"] = 'ELGS_09';  $ship_code_array[107]['name'] = 'Exel Logistics - Delivery and Install';		
$ship_code_array[108]["code"] = 'ELGS_DS';  $ship_code_array[108]['name'] = 'Exel Logistics - Threshold Service';		
$ship_code_array[109]["code"] = 'EXDO';  $ship_code_array[109]['name'] = 'Expeditor"s International of Washington';		
$ship_code_array[110]["code"] = 'EXNS';  $ship_code_array[110]['name'] = 'Express Transport';		
$ship_code_array[111]["code"] = 'EXNS_SE';  $ship_code_array[111]['name'] = 'Express Transport - 2nd Day';		
$ship_code_array[112]["code"] = 'FMTP_G2';  $ship_code_array[112]['name'] = 'Farmore Transportation Services - Basic Service';		
$ship_code_array[113]["code"] = 'FMTP_DS';  $ship_code_array[113]['name'] = 'Farmore Transportation Services -Threshold Service';		
$ship_code_array[114]["code"] = 'FASC';  $ship_code_array[114]['name'] = 'Fastfrate';		
$ship_code_array[115]["code"] = 'FASC_G2';  $ship_code_array[115]['name'] = 'Fastfrate - Basic Service';		
$ship_code_array[116]["code"] = 'FASC_09';  $ship_code_array[116]['name'] = 'Fastfrate - Delivery and Install';		
$ship_code_array[117]["code"] = 'FASC_DS';  $ship_code_array[117]['name'] = 'Fastfrate - Threshold Service';		
$ship_code_array[118]["code"] = 'FSTK_G2';  $ship_code_array[118]['name'] = 'Fastrek - Basic Service';		
$ship_code_array[119]["code"] = 'FSTK_DS';  $ship_code_array[119]['name'] = 'Fastrek - Threshold Service';		
$ship_code_array[120]["code"] = 'FDLG_DS';  $ship_code_array[120]['name'] = 'Federal Logistics Inc. - Threshold Service';	
$ship_code_array[121]["code"] = 'FEDX_SE';  $ship_code_array[121]['name'] = 'Fedex 2nd Day';		
$ship_code_array[122]["code"] = 'FEDF';  $ship_code_array[122]['name'] = 'FEDEX Freight';		
$ship_code_array[123]["code"] = 'FXFC';  $ship_code_array[123]['name'] = 'Fedex Freight Canada';		
$ship_code_array[124]["code"] = 'FEDX_CG';  $ship_code_array[124]['name'] = 'Fedex Ground';		
$ship_code_array[125]["code"] = 'FEDX_09';  $ship_code_array[125]['name'] = 'FEDEX Home Service';		
$ship_code_array[126]["code"] = 'FDE_IE';  $ship_code_array[126]['name'] = 'FEDEX International Economy';		
$ship_code_array[127]["code"] = 'FDE_SG';  $ship_code_array[127]['name'] = 'FEDEX International Ground';		
$ship_code_array[128]["code"] = 'FDE_IX';  $ship_code_array[128]['name'] = 'FEDEX International Priority';		
$ship_code_array[129]["code"] = 'FXNL';  $ship_code_array[129]['name'] = 'Fedex National LTL';		
$ship_code_array[130]["code"] = 'FEDX_ND';  $ship_code_array[130]['name'] = 'Fedex Next Day';		
$ship_code_array[131]["code"] = 'FXSP';  $ship_code_array[131]['name'] = 'Fedex SmartPost';		
$ship_code_array[132]["code"] = 'FEDX_3D';  $ship_code_array[132]['name'] = 'Fedex Three Day';		
$ship_code_array[133]["code"] = 'FSCF_G2';  $ship_code_array[133]['name'] = 'Frontier Supply Chain Solutions - Basic';		
$ship_code_array[134]["code"] = 'FSCF_09';  $ship_code_array[134]['name'] = 'Frontier Supply Chain Solutions - Install';		
$ship_code_array[135]["code"] = 'FSCF_DS';  $ship_code_array[135]['name'] = 'Frontier Supply Chain Solutions - Threshold';		
$ship_code_array[136]["code"] = 'GCMP';  $ship_code_array[136]['name'] = 'Genwest';		
$ship_code_array[137]["code"] = 'GLLD';  $ship_code_array[137]['name'] = 'Glenncoe Transport';		
$ship_code_array[138]["code"] = 'GELJ';  $ship_code_array[138]['name'] = 'Globaltranz';		
$ship_code_array[139]["code"] = 'GBCF_G2';  $ship_code_array[139]['name'] = 'GlobeCon Freight Systems - Basic Service';		
$ship_code_array[140]["code"] = 'GBCF_09';  $ship_code_array[140]['name'] = 'GlobeCon Freight Systems - Deliver and Install';		
$ship_code_array[141]["code"] = 'GBCF_DS';  $ship_code_array[141]['name'] = 'GlobeCon Freight Systems - Threshold Service';		
$ship_code_array[142]["code"] = 'GLDI';  $ship_code_array[142]['name'] = 'Glova-Link Distribution';		
$ship_code_array[143]["code"] = 'GLDI_G2';  $ship_code_array[143]['name'] = 'Glova-Link Distribution - Basic Service';		
$ship_code_array[144]["code"] = 'GFXP_DS';  $ship_code_array[144]['name'] = 'Ground Freight Expeditors - Threshold Service';		
$ship_code_array[145]["code"] = 'HLGR_G2';  $ship_code_array[145]['name'] = 'Harrah Logistics - Basic Service';		
$ship_code_array[146]["code"] = 'HLGR_09';  $ship_code_array[146]['name'] = 'Harrah Logistics - Delivery and Install';		
$ship_code_array[147]["code"] = 'HLGR_DS';  $ship_code_array[147]['name'] = 'Harrah Logistics - Threshold Service';		
$ship_code_array[148]["code"] = 'POLN';  $ship_code_array[148]['name'] = 'Hellman Worldwide Logistics';		
$ship_code_array[149]["code"] = 'HDIR_G2';  $ship_code_array[149]['name'] = 'HEP Direct - Basic Service';		
$ship_code_array[150]["code"] = 'HDIR_09';  $ship_code_array[150]['name'] = 'HEP Direct - Delivery and Install';		
$ship_code_array[151]["code"] = 'HDIR_DS';  $ship_code_array[151]['name'] = 'HEP Direct - Threshold Service';		
$ship_code_array[152]["code"] = 'HRCF_G2';  $ship_code_array[152]['name'] = 'Hercules Freight - Basic Service';		
$ship_code_array[153]["code"] = 'HRCF_09';  $ship_code_array[153]['name'] = 'Hercules Freight - Delivery and Install';		
$ship_code_array[154]["code"] = 'HRCF_DS';  $ship_code_array[154]['name'] = 'Hercules Freight - Threshold Service';		
$ship_code_array[155]["code"] = 'HWDQ_G2';  $ship_code_array[155]['name'] = 'Hollywood Delivery Services - Basic Service';		
$ship_code_array[156]["code"] = 'BEKN_G2';  $ship_code_array[156]['name'] = 'Home Direct USA - Basic Service';		
$ship_code_array[157]["code"] = 'BEKN_09';  $ship_code_array[157]['name'] = 'Home Direct USA - Premium (White Glove)';		
$ship_code_array[158]["code"] = 'BEKN_DS';  $ship_code_array[158]['name'] = 'Home Direct USA - Threshold Service';		
$ship_code_array[159]["code"] = 'HJBT_G2';  $ship_code_array[159]['name'] = 'JB Hunt - Basic Service';		
$ship_code_array[160]["code"] = 'HJBT_09';  $ship_code_array[160]['name'] = 'JB Hunt - Delivery and Install';		
$ship_code_array[161]["code"] = 'HJBT_DS';  $ship_code_array[161]['name'] = 'JB Hunt - Threshold Service';		
$ship_code_array[162]["code"] = 'KLIQ_G2';  $ship_code_array[162]['name'] = 'Kansas Logistics - Basic Service';		
$ship_code_array[163]["code"] = 'KIDY';  $ship_code_array[163]['name'] = 'Kindersley Transport';		
$ship_code_array[164]["code"] = 'KIDY_G2';  $ship_code_array[164]['name'] = 'Kindersley Transport - Basic Service';		
$ship_code_array[165]["code"] = 'KTAI_G2';  $ship_code_array[165]['name'] = 'Kingsway Transport - Basic Service';		
$ship_code_array[166]["code"] = 'KTAI_09';  $ship_code_array[166]['name'] = 'Kingsway Transport - Delivery and Install';		
$ship_code_array[167]["code"] = 'KTAI_DS';  $ship_code_array[167]['name'] = 'Kingsway Transport - Threshold Service';		
$ship_code_array[168]["code"] = 'KKWQ';  $ship_code_array[168]['name'] = 'KKW Trucking Inc.';	
$ship_code_array[169]["code"] = 'KKWQ_G2';  $ship_code_array[169]['name'] = 'KKW Trucking Inc. - Basic Service';	
$ship_code_array[170]["code"] = 'LKVL';  $ship_code_array[170]['name'] = 'Lakeville Motor Express Inc.';	
$ship_code_array[171]["code"] = 'LIGS_G2';  $ship_code_array[171]['name'] = 'Landstar - Basic Service';		
$ship_code_array[172]["code"] = 'LIGS_09';  $ship_code_array[172]['name'] = 'Landstar - Delivery and Install';		
$ship_code_array[173]["code"] = 'LMEF_G2';  $ship_code_array[173]['name'] = 'Loomis Express - Basic Service';		
$ship_code_array[174]["code"] = 'LTL';  $ship_code_array[174]['name'] = 'LTL (service unspecified)';		
$ship_code_array[175]["code"] = 'LTL_G2';  $ship_code_array[175]['name'] = 'LTL Basic Service';		
$ship_code_array[176]["code"] = 'LTL_DS';  $ship_code_array[176]['name'] = 'LTL Threshold Service';		
$ship_code_array[177]["code"] = 'LTL_09';  $ship_code_array[177]['name'] = 'LTL White Glove';		
$ship_code_array[178]["code"] = 'LYAF_SE';  $ship_code_array[178]['name'] = 'Lynden Transport 2 Day Saver';		
$ship_code_array[179]["code"] = 'LYAF_G2';  $ship_code_array[179]['name'] = 'Lynden Transport Curbside Delivery';		
$ship_code_array[180]["code"] = 'LYAF_ND';  $ship_code_array[180]['name'] = 'Lynden Transport Next Day Priority';		
$ship_code_array[181]["code"] = 'LTIA_DS';  $ship_code_array[181]['name'] = 'Lynden Transport Threshold Service';		
$ship_code_array[182]["code"] = 'LTIA_09';  $ship_code_array[182]['name'] = 'Lynden White Glove';		
$ship_code_array[183]["code"] = 'MFRC_G2';  $ship_code_array[183]['name'] = 'Mainfreight - Basic Service';		
$ship_code_array[184]["code"] = 'MFRC_09';  $ship_code_array[184]['name'] = 'Mainfreight - Delivery and Install';		
$ship_code_array[185]["code"] = 'MFRC_DS';  $ship_code_array[185]['name'] = 'Mainfreight - Threshold Service';		
$ship_code_array[186]["code"] = 'MYRY_G2';  $ship_code_array[186]['name'] = 'Mallory Alexander - Basic Service';		
$ship_code_array[187]["code"] = 'MYRY_09';  $ship_code_array[187]['name'] = 'Mallory Alexander - Delivery and Install';		
$ship_code_array[188]["code"] = 'MANI_G2';  $ship_code_array[188]['name'] = 'Manitoulin Transport - Basic Service';		
$ship_code_array[189]["code"] = 'MANI_09';  $ship_code_array[189]['name'] = 'Manitoulin Transport - Delivery and Install';		
$ship_code_array[190]["code"] = 'MANI_DS';  $ship_code_array[190]['name'] = 'Manitoulin Transport - Threshold Service';		
$ship_code_array[191]["code"] = 'MFSY';  $ship_code_array[191]['name'] = 'Manna Distribution Services';		
$ship_code_array[192]["code"] = 'MFSY_09';  $ship_code_array[192]['name'] = 'Manna Distribution Services - Delivery and Install';		
$ship_code_array[193]["code"] = 'MFSY_DS';  $ship_code_array[193]['name'] = 'Manna Distribution Services - Threshold Service';		
$ship_code_array[194]["code"] = 'MFAF';  $ship_code_array[194]['name'] = 'Matheson Fast Freight Inc.';		
$ship_code_array[195]["code"] = 'MXZN_G2';  $ship_code_array[195]['name'] = 'Mazin Furniture - Basic Service';		
$ship_code_array[196]["code"] = 'MXZN_09';  $ship_code_array[196]['name'] = 'Mazin Furniture - Delivery and Install';		
$ship_code_array[197]["code"] = 'MXZN_DS';  $ship_code_array[197]['name'] = 'Mazin Furniture - Threshold Service';		
$ship_code_array[198]["code"] = 'MDLD';  $ship_code_array[198]['name'] = 'Midland Transport LTL Service';		
$ship_code_array[199]["code"] = 'MTVL_G2';  $ship_code_array[199]['name'] = 'Mountain Valley Express - Basic Service';		
$ship_code_array[200]["code"] = 'NLSJ_G2';  $ship_code_array[200]['name'] = 'National Logistics Services - Basic Service';		
$ship_code_array[201]["code"] = 'NLSJ_09';  $ship_code_array[201]['name'] = 'National Logistics Services - Delivery and Install';		
$ship_code_array[202]["code"] = 'NLSJ_DS';  $ship_code_array[202]['name'] = 'National Logistics Services - Threshold Service';		
$ship_code_array[203]["code"] = 'NEBT_DS';  $ship_code_array[203]['name'] = 'Nebraska Trucking Company - Threshold';		
$ship_code_array[204]["code"] = 'NEMF_G2';  $ship_code_array[204]['name'] = 'New England Motor Freight - Basic Service';		
$ship_code_array[205]["code"] = 'NPME_G2';  $ship_code_array[205]['name'] = 'New Penn Motor Express - Basic Service';		
$ship_code_array[206]["code"] = 'NDLV_G2';  $ship_code_array[206]['name'] = 'NonstopDelivery - Basic Service';		
$ship_code_array[207]["code"] = 'NDLV_GP';  $ship_code_array[207]['name'] = 'NonstopDelivery - Delivery Install and Haul Away';	
$ship_code_array[208]["code"] = 'NDLV_DS';  $ship_code_array[208]['name'] = 'NonstopDelivery - Threshold Service';		
$ship_code_array[209]["code"] = 'NORM';  $ship_code_array[209]['name'] = 'Normandin truck carrier';		
$ship_code_array[210]["code"] = 'NUMK_G2';  $ship_code_array[210]['name'] = 'Numark Transportation - Basic Service';		
$ship_code_array[211]["code"] = 'NVCP_G2';  $ship_code_array[211]['name'] = 'NVC Logistics - Basic Service';		
$ship_code_array[212]["code"] = 'NVCP_09';  $ship_code_array[212]['name'] = 'NVC Logistics - Delivery and Install';		
$ship_code_array[213]["code"] = 'NVCP_DS';  $ship_code_array[213]['name'] = 'NVC Logistics - Threshold Service';		
$ship_code_array[214]["code"] = 'OAKH_G2';  $ship_code_array[214]['name'] = 'Oak Harbor Freight Lines Inc. - Basic Service';	
$ship_code_array[215]["code"] = 'ODFL';  $ship_code_array[215]['name'] = 'Old Dominion';		
$ship_code_array[216]["code"] = 'ODFL_G2';  $ship_code_array[216]['name'] = 'Old Dominion - Basic Service';		
$ship_code_array[217]["code"] = 'ODFL_09';  $ship_code_array[217]['name'] = 'Old Dominion - Delivery and Install';		
$ship_code_array[218]["code"] = 'ODFL_DS';  $ship_code_array[218]['name'] = 'Old Dominion - Threshold Service';		
$ship_code_array[219]["code"] = 'EMSY_G2';  $ship_code_array[219]['name'] = 'Ontrac - Basic Service';		
$ship_code_array[220]["code"] = 'OTHR';  $ship_code_array[220]['name'] = 'Other';		
$ship_code_array[221]["code"] = 'OVNT';  $ship_code_array[221]['name'] = 'Overnite';		
$ship_code_array[222]["code"] = 'PENS_G2';  $ship_code_array[222]['name'] = 'Peninsula Truck Lines - Basic Service';		
$ship_code_array[223]["code"] = 'PTSL_G2';  $ship_code_array[223]['name'] = 'Penner International - Basic Service';		
$ship_code_array[224]["code"] = 'PAAF';  $ship_code_array[224]['name'] = 'Pilot Freight Services';		
$ship_code_array[225]["code"] = 'PAAF_G2';  $ship_code_array[225]['name'] = 'Pilot Freight Services - Basic Service';		
$ship_code_array[226]["code"] = 'PAAF_09';  $ship_code_array[226]['name'] = 'Pilot Freight Services - Delivery and Install';		
$ship_code_array[227]["code"] = 'PAAF_DS';  $ship_code_array[227]['name'] = 'Pilot Freight Services - Threshold Service';		
$ship_code_array[228]["code"] = 'PITD';  $ship_code_array[228]['name'] = 'PITT Ohio';		
$ship_code_array[229]["code"] = 'DPIT';  $ship_code_array[229]['name'] = 'PITT Ohio/Direct Ship';		
$ship_code_array[230]["code"] = 'PCLH';  $ship_code_array[230]['name'] = 'Platinum Cargo Logistics';		
$ship_code_array[231]["code"] = 'PCLH_09';  $ship_code_array[231]['name'] = 'Platinum Cargo Logistics - Delivery and Install';		
$ship_code_array[232]["code"] = 'PCLH_DS';  $ship_code_array[232]['name'] = 'Platinum Cargo Logistics - Threshold Service';		
$ship_code_array[233]["code"] = 'PLYC_09';  $ship_code_array[233]['name'] = 'Plycon Transportation - Delivery and Install';	
$ship_code_array[234]["code"] = 'ATVL_G2';  $ship_code_array[234]['name'] = 'Primex Global Services - Basic Service';		
$ship_code_array[235]["code"] = 'PAXA';  $ship_code_array[235]['name'] = 'Priority Solutions International';		
$ship_code_array[236]["code"] = 'PRLA_SE';  $ship_code_array[236]['name'] = 'Purolator Courier 2nd day';	
$ship_code_array[237]["code"] = 'PRLA_CG';  $ship_code_array[237]['name'] = 'Purolator Courier ground';	
$ship_code_array[238]["code"] = 'PRFR_G2';  $ship_code_array[238]['name'] = 'Purolator Freight - Basic Service';		
$ship_code_array[239]["code"] = 'QKNE_ND';  $ship_code_array[239]['name'] = 'QRC Logistics Ltd. - Next Day';		
$ship_code_array[240]["code"] = 'QXTI';  $ship_code_array[240]['name'] = 'QuikX Transportation';		
$ship_code_array[241]["code"] = 'QXTI_G2';  $ship_code_array[241]['name'] = 'QuikX Transportation - Basic Service';		
$ship_code_array[242]["code"] = 'RNLO';  $ship_code_array[242]['name'] = 'R & L Carriers';		
$ship_code_array[243]["code"] = 'RNLO_SE';  $ship_code_array[243]['name'] = 'R & L Carriers - 2nd Day';		
$ship_code_array[244]["code"] = 'RNLO_G2';  $ship_code_array[244]['name'] = 'R & L Carriers - Basic Service';		
$ship_code_array[245]["code"] = 'RNLO_ND';  $ship_code_array[245]['name'] = 'R & L Carriers - Next Day';		
$ship_code_array[246]["code"] = 'RNLO_DS';  $ship_code_array[246]['name'] = 'R & L Carriers - Threshold Service';		
$ship_code_array[247]["code"] = 'RDFS_G2';  $ship_code_array[247]['name'] = 'Road Runner - Basic Service';
$ship_code_array[248]["code"] = 'RDFS_09';  $ship_code_array[248]['name'] = 'Road Runner - Delivery and Install';		
$ship_code_array[249]["code"] = 'RDFS_DS';  $ship_code_array[249]['name'] = 'Road Runner - Threshold Service';		
$ship_code_array[250]["code"] = 'RDWY';  $ship_code_array[250]['name'] = 'Roadway';		
$ship_code_array[251]["code"] = 'TRRB';  $ship_code_array[251]['name'] = 'Robert Transport';		
$ship_code_array[252]["code"] = 'SAIA';  $ship_code_array[252]['name'] = 'Saia Motor Freight';		
$ship_code_array[253]["code"] = 'SDCR_09';  $ship_code_array[253]['name'] = 'Sameday Worldwide - Delivery and Install';		
$ship_code_array[254]["code"] = 'SDCR_CG';  $ship_code_array[254]['name'] = 'Sameday Worldwide - Expedited Ground';		
$ship_code_array[255]["code"] = 'SDCR_DS';  $ship_code_array[255]['name'] = 'Sameday Worldwide - Threshold Service';		
$ship_code_array[256]["code"] = 'SEUE';  $ship_code_array[256]['name'] = 'Security Express';		
$ship_code_array[257]["code"] = 'SEKW_09';  $ship_code_array[257]['name'] = 'Seko - Delivery Install Haul Away';
$ship_code_array[258]["code"] = 'SEKW_DS';  $ship_code_array[258]['name'] = 'Seko - Threshold Service';		
$ship_code_array[259]["code"] = 'SEKW';  $ship_code_array[259]['name'] = 'Seko Standard';		
$ship_code_array[260]["code"] = 'SNDY';  $ship_code_array[260]['name'] = 'Select Thibodeau';		
$ship_code_array[261]["code"] = 'SNDY_G2';  $ship_code_array[261]['name'] = 'Select Thibodeau - Basic Service';		
$ship_code_array[262]["code"] = 'SVBA';  $ship_code_array[262]['name'] = 'Service By Air';		
$ship_code_array[263]["code"] = 'SBDA_G2';  $ship_code_array[263]['name'] = 'Service by Dawn - Basic Service';		
$ship_code_array[264]["code"] = 'SBDA_09';  $ship_code_array[264]['name'] = 'Service by Dawn - Delivery and Install';		
$ship_code_array[275]["code"] = 'SBDA_DS';  $ship_code_array[275]['name'] = 'Service by Dawn - Threshold Service';		
$ship_code_array[266]["code"] = 'SHA';  $ship_code_array[266]['name'] = 'Shaw private carrier';		
$ship_code_array[267]["code"] = 'SMTM_CG';  $ship_code_array[267]['name'] = 'Smart Mail (USPS Affiliate)';		
$ship_code_array[268]["code"] = 'SEFL';  $ship_code_array[268]['name'] = 'Southeastern Freight Lines';		
$ship_code_array[269]["code"] = 'SEFL_G2';  $ship_code_array[269]['name'] = 'Southeastern Freight Lines - Basic Service';		
$ship_code_array[270]["code"] = 'SMF_ND';  $ship_code_array[270]['name'] = 'Special Moments Flowers & Gifts Ltd.';		
$ship_code_array[271]["code"] = 'SPCG';  $ship_code_array[271]['name'] = 'Specialized Transportation';		
$ship_code_array[272]["code"] = 'SPCG_09';  $ship_code_array[272]['name'] = 'Specialized Transportation - Delivery and Install';		
$ship_code_array[273]["code"] = 'SPCG_DS';  $ship_code_array[273]['name'] = 'Specialized Transportation - Threshold Service';		
$ship_code_array[274]["code"] = 'SPED';  $ship_code_array[274]['name'] = 'Spee Dee Delivery Service Inc.';	
$ship_code_array[275]["code"] = 'SSDS_G2';  $ship_code_array[275]['name'] = 'Speedy Spa Delivery - Basic Service';		
$ship_code_array[276]["code"] = 'BUFM_G2';  $ship_code_array[276]['name'] = 'Speedy Transport - Basic Service';		
$ship_code_array[277]["code"] = 'BUFM_DS';  $ship_code_array[277]['name'] = 'Speedy Transport - Threshold Service';		
$ship_code_array[278]["code"] = 'SUND_09';  $ship_code_array[278]['name'] = 'Sun Delivery Inc. - Delivery and Install';	
$ship_code_array[279]["code"] = 'SXLX_G2';  $ship_code_array[279]['name'] = 'Suntrax Logistics - Basic Service';		
$ship_code_array[280]["code"] = 'SXLX_09';  $ship_code_array[280]['name'] = 'Suntrax Logistics - Delivery and Install';		
$ship_code_array[281]["code"] = 'SXLX_DS';  $ship_code_array[281]['name'] = 'Suntrax Logistics - Threshold Service';		
$ship_code_array[282]["code"] = 'DELL_CG';  $ship_code_array[282]['name'] = 'Tandem Carriers - UPS and Purolator';		
$ship_code_array[283]["code"] = 'TLF_SE';  $ship_code_array[283]['name'] = 'Teleflora Fulfillment Network - 2nd Day';		
$ship_code_array[284]["code"] = 'TLF_CG';  $ship_code_array[284]['name'] = 'Teleflora Fulfillment Network - Ground';		
$ship_code_array[285]["code"] = 'TLF_ND';  $ship_code_array[285]['name'] = 'Teleflora Fulfillment Network - Next Day';		
$ship_code_array[286]["code"] = 'TDAH_G2';  $ship_code_array[286]['name'] = 'Total Transportation Services-Basic Service';		
$ship_code_array[287]["code"] = 'TDAH_09';  $ship_code_array[287]['name'] = 'Total Transportation Services-Delivery and Install';		
$ship_code_array[288]["code"] = 'TDAH_DS';  $ship_code_array[288]['name'] = 'Total Transportation Services-Threshold';		
$ship_code_array[289]["code"] = 'TTLQ';  $ship_code_array[289]['name'] = 'TotalLine Transport';		
$ship_code_array[290]["code"] = 'TFFC_G2';  $ship_code_array[290]['name'] = 'Traffic Tech - Basic Service';		
$ship_code_array[291]["code"] = 'TFFC_09';  $ship_code_array[291]['name'] = 'Traffic Tech - Delivery and Install';		
$ship_code_array[292]["code"] = 'TFFC_DS';  $ship_code_array[292]['name'] = 'Traffic Tech - Threshold Service';		
$ship_code_array[293]["code"] = 'TLIE_G2';  $ship_code_array[293]['name'] = 'Trail Lines - Basic Service';		
$ship_code_array[294]["code"] = 'TLIE_09';  $ship_code_array[294]['name'] = 'Trail Lines - Delivery and Install';		
$ship_code_array[295]["code"] = 'TLIE_DS';  $ship_code_array[295]['name'] = 'Trail Lines - Threshold Service';		
$ship_code_array[296]["code"] = 'TRWE';  $ship_code_array[296]['name'] = 'Transaction Wireless';		
$ship_code_array[297]["code"] = 'TWLP';  $ship_code_array[297]['name'] = 'Transwest';		
$ship_code_array[298]["code"] = 'PTQL_G2';  $ship_code_array[298]['name'] = 'TST Overland Express - Basic Service';		
$ship_code_array[299]["code"] = 'UNSP';  $ship_code_array[299]['name'] = 'Unspecified';		
$ship_code_array[300]["code"] = 'UPSN_SE';  $ship_code_array[300]['name'] = 'UPS 2nd Day Air';		
$ship_code_array[301]["code"] = 'UPSET_SE';  $ship_code_array[301]['name'] = 'UPS 2nd Day Air Signature Required';	
$ship_code_array[302]["code"] = 'UPSN_3D';  $ship_code_array[302]['name'] = 'UPS 3 Day Select';		
$ship_code_array[303]["code"] = 'UPSC_ND';  $ship_code_array[303]['name'] = 'UPS Express Saver (Next Day)';		
$ship_code_array[304]["code"] = 'UPGS';  $ship_code_array[304]['name'] = 'UPS Freight (service level unspecified)';		
$ship_code_array[305]["code"] = 'UPGF_G2';  $ship_code_array[305]['name'] = 'UPS Freight - Basic Service';		
$ship_code_array[306]["code"] = 'UPSN_CG';  $ship_code_array[306]['name'] = 'UPS Ground';		
$ship_code_array[307]["code"] = 'UPSET_CG';  $ship_code_array[307]['name'] = 'UPS Ground Signature Required';	
$ship_code_array[308]["code"] = 'UPSN_FC';  $ship_code_array[308]['name'] = 'UPS Mail Innovations - Standard';		
$ship_code_array[309]["code"] = 'UPSN_ND';  $ship_code_array[309]['name'] = 'UPS Next Day Air';		
$ship_code_array[310]["code"] = 'UPSET_ND';  $ship_code_array[310]['name'] = 'UPS Next Day Air Signature Required';	
$ship_code_array[311]["code"] = 'HMES';  $ship_code_array[311]['name'] = 'USF Holland';		
$ship_code_array[312]["code"] = 'RETL';  $ship_code_array[312]['name'] = 'USF Reddaway';		
$ship_code_array[313]["code"] = 'USPS_ND';  $ship_code_array[313]['name'] = 'USPS Express Mail';		
$ship_code_array[314]["code"] = 'USPSB_FC';  $ship_code_array[314]['name'] = 'USPS First Class Mail';		
$ship_code_array[315]["code"] = 'USPS_BC';  $ship_code_array[315]['name'] = 'USPS Package Services (Parcel Post)';		
$ship_code_array[316]["code"] = 'USPS_PO';  $ship_code_array[316]['name'] = 'USPS Periodicals';		
$ship_code_array[317]["code"] = 'USPS_PB';  $ship_code_array[317]['name'] = 'USPS Priority Mail';		
$ship_code_array[318]["code"] = 'VKMF_G2';  $ship_code_array[318]['name'] = 'Van Kam Freightways - Basic Service';		
$ship_code_array[319]["code"] = 'LDSI_G2';  $ship_code_array[319]['name'] = 'Vast+Lodeso - Basic Service';		
$ship_code_array[320]["code"] = 'LDSI_09';  $ship_code_array[320]['name'] = 'Vast+Lodeso - Delivery and Install';		
$ship_code_array[321]["code"] = 'LDSI_DS';  $ship_code_array[321]['name'] = 'Vast+Lodeso - Threshold Service';		
$ship_code_array[322]["code"] = 'VSXP';  $ship_code_array[322]['name'] = 'Vision Express';		
$ship_code_array[323]["code"] = 'VSXP_G2';  $ship_code_array[323]['name'] = 'Vision Express - Basic Service';		
$ship_code_array[324]["code"] = 'VITY';  $ship_code_array[324]['name'] = 'Vitran Canada';		
$ship_code_array[325]["code"] = 'VITY_G2';  $ship_code_array[325]['name'] = 'Vitran Canada - Basic Service';		
$ship_code_array[326]["code"] = 'VITR';  $ship_code_array[326]['name'] = 'Vitran Express';		
$ship_code_array[327]["code"] = 'WARD';  $ship_code_array[327]['name'] = 'WARD Trucking';		
$ship_code_array[328]["code"] = 'WWAT';  $ship_code_array[328]['name'] = 'Watkins';		
$ship_code_array[329]["code"] = 'WKSH_G2';  $ship_code_array[329]['name'] = 'Watkins Shepard Trucking Inc. - Basic Service';	
$ship_code_array[330]["code"] = 'WKSH_DS';  $ship_code_array[330]['name'] = 'Watkins Shepard Trucking Inc. - Threshold Service';	
$ship_code_array[331]["code"] = 'WCNE_CG';  $ship_code_array[331]['name'] = 'Western Canada Express';		
$ship_code_array[332]["code"] = 'WGLS';  $ship_code_array[332]['name'] = 'Western Logistics';		
$ship_code_array[333]["code"] = 'WTVA_09';  $ship_code_array[333]['name'] = 'Wilson Trucking -  Delivery and Install';		
$ship_code_array[334]["code"] = 'WTVA_G2';  $ship_code_array[334]['name'] = 'Wilson Trucking - Basic Service';		
$ship_code_array[335]["code"] = 'WTVA_DS';  $ship_code_array[335]['name'] = 'Wilson Trucking - Threshold Service';		
$ship_code_array[336]["code"] = 'XGSI_G2';  $ship_code_array[336]['name'] = 'Xpress Global Systems - Basic Service';		
$ship_code_array[337]["code"] = 'YFSY';  $ship_code_array[337]['name'] = 'Yellow';		
$ship_code_array[338]["code"] = 'RDWY_G2';  $ship_code_array[338]['name'] = 'YRC - Basic Service';		
$ship_code_array[339]["code"] = 'RDWY_09';  $ship_code_array[339]['name'] = 'YRC - Delivery and Install';		
$ship_code_array[340]["code"] = 'RDWY_ES';  $ship_code_array[340]['name'] = 'YRC - Expedited Delivery';		
$ship_code_array[341]["code"] = 'RDWY_DS';  $ship_code_array[341]['name'] = 'YRC - Threshold Service';		
$ship_code_array[342]["code"] = 'ZEFL_09';  $ship_code_array[342]['name'] = 'Zenith Global Logistics - Delivery and Install';	

?>
